# Generated by Django 4.1.2 on 2022-11-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kvalifikaciya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opyt', models.CharField(max_length=20, verbose_name='Опыт')),
                ('procent', models.FloatField(verbose_name='Процент')),
            ],
        ),
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('opisanie', models.TextField(verbose_name='Описание')),
                ('stoimost', models.IntegerField(verbose_name='Стоимость')),
                ('foto', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Pricheski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('opisanie', models.TextField(verbose_name='Описание')),
                ('stoimost', models.IntegerField(verbose_name='Стоимость')),
                ('foto', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Vizajisti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('foto', models.ImageField(upload_to='', verbose_name='Фото')),
                ('kvalifikaciya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.kvalifikaciya', verbose_name='Квалификация')),
            ],
        ),
        migrations.CreateModel(
            name='Zayavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_klient', models.CharField(max_length=20, verbose_name='Имя')),
                ('telephon', models.CharField(max_length=18, verbose_name='Телефон')),
                ('data_sozd', models.DateTimeField(auto_now=True)),
                ('data_vypoln', models.DateTimeField(verbose_name='Дата и время')),
                ('makeup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.makeup', verbose_name='Макияж')),
                ('pricheski', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.pricheski', verbose_name='Причёска')),
                ('vizajist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.vizajisti', verbose_name='Визажист')),
            ],
        ),
    ]
