# Generated by Django 4.1.2 on 2022-11-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeup',
            name='foto',
            field=models.ImageField(upload_to='makeup/'),
        ),
        migrations.AlterField(
            model_name='pricheski',
            name='foto',
            field=models.ImageField(upload_to='pricheski/'),
        ),
        migrations.AlterField(
            model_name='vizajisti',
            name='foto',
            field=models.ImageField(upload_to='vizajisti/'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='makeup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='content.makeup', verbose_name='Макияж'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='pricheski',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='content.pricheski', verbose_name='Причёска'),
        ),
    ]
